import type { Member } from "./typeMember";

// Beispiel-Daten
import type { Member } from "./typeMember";

// Beispiel-Daten
export const members: Member[] = [
  {
    mitgliedsnummer: 1,
    vorname: "Anna",
    nachname: "Müller",
    alter: 28,
    bezahlt: true,
    aktiv: true,
    mitgliedSeit: "2021-03-15",
    email: "anna.mueller@example.com",
  },
  {
    mitgliedsnummer: 2,
    vorname: "Ben",
    nachname: "Schmidt",
    alter: 34,
    bezahlt: false,
    aktiv: false,
    mitgliedSeit: "2020-06-01",
    email: "ben.schmidt@example.com",
  },
  {
    mitgliedsnummer: 3,
    vorname: "Clara",
    nachname: "Klein",
    alter: 22,
    bezahlt: true,
    aktiv: true,
    mitgliedSeit: "2023-01-10",
    email: "clara.klein@example.com",
  },
  {
    mitgliedsnummer: 4,
    vorname: "David",
    nachname: "Becker",
    alter: 45,
    bezahlt: true,
    aktiv: true,
    mitgliedSeit: "2019-09-22",
    email: "david.becker@example.com",
  },
  {
    mitgliedsnummer: 5,
    vorname: "Eva",
    nachname: "Fischer",
    alter: 31,
    bezahlt: false,
    aktiv: false,
    mitgliedSeit: "2022-04-05",
    email: "eva.fischer@example.com",
  },
  {
    mitgliedsnummer: 6,
    vorname: "Felix",
    nachname: "Wagner",
    alter: 29,
    bezahlt: true,
    aktiv: true,
    mitgliedSeit: "2020-11-11",
    email: "felix.wagner@example.com",
  },
  {
    mitgliedsnummer: 7,
    vorname: "Gina",
    nachname: "Lorenz",
    alter: 27,
    bezahlt: false,
    aktiv: false,
    mitgliedSeit: "2021-07-03",
    email: "gina.lorenz@example.com",
  },
  {
    mitgliedsnummer: 8,
    vorname: "Hans",
    nachname: "Koch",
    alter: 53,
    bezahlt: true,
    aktiv: true,
    mitgliedSeit: "2018-12-19",
    email: "hans.koch@example.com",
  },
  {
    mitgliedsnummer: 9,
    vorname: "Isabel",
    nachname: "Schäfer",
    alter: 39,
    bezahlt: false,
    aktiv: false,
    mitgliedSeit: "2023-06-30",
    email: "isabel.schaefer@example.com",
  },
  {
    mitgliedsnummer: 10,
    vorname: "Jonas",
    nachname: "Krüger",
    alter: 24,
    bezahlt: true,
    aktiv: true,
    mitgliedSeit: "2022-08-25",
    email: "jonas.krueger@example.com",
  },
  {
    mitgliedsnummer: 11,
    vorname: "Katharina",
    nachname: "Seidel",
    alter: 37,
    bezahlt: true,
    aktiv: true,
    mitgliedSeit: "2020-10-10",
    email: "katharina.seidel@example.com",
  },
  {
    mitgliedsnummer: 12,
    vorname: "Leo",
    nachname: "Winter",
    alter: 30,
    bezahlt: false,
    aktiv: false,
    mitgliedSeit: "2021-01-05",
    email: "leo.winter@example.com",
  },
  {
    mitgliedsnummer: 13,
    vorname: "Maria",
    nachname: "Berger",
    alter: 26,
    bezahlt: true,
    aktiv: true,
    mitgliedSeit: "2023-02-14",
    email: "maria.berger@example.com",
  },
  {
    mitgliedsnummer: 14,
    vorname: "Noah",
    nachname: "Brandt",
    alter: 33,
    bezahlt: false,
    aktiv: false,
    mitgliedSeit: "2022-03-17",
    email: "noah.brandt@example.com",
  },
  {
    mitgliedsnummer: 15,
    vorname: "Olivia",
    nachname: "Franke",
    alter: 40,
    bezahlt: true,
    aktiv: true,
    mitgliedSeit: "2019-05-23",
    email: "olivia.franke@example.com",
  },
  {
    mitgliedsnummer: 16,
    vorname: "Paul",
    nachname: "Lang",
    alter: 35,
    bezahlt: true,
    aktiv: true,
    mitgliedSeit: "2020-07-12",
    email: "paul.lang@example.com",
  },
  {
    mitgliedsnummer: 17,
    vorname: "Quirin",
    nachname: "Hartmann",
    alter: 21,
    bezahlt: false,
    aktiv: false,
    mitgliedSeit: "2024-01-01",
    email: "quirin.hartmann@example.com",
  },
  {
    mitgliedsnummer: 18,
    vorname: "Rosa",
    nachname: "Scholz",
    alter: 44,
    bezahlt: true,
    aktiv: true,
    mitgliedSeit: "2017-04-04",
    email: "rosa.scholz@example.com",
  },
  {
    mitgliedsnummer: 19,
    vorname: "Simon",
    nachname: "Keller",
    alter: 38,
    bezahlt: false,
    aktiv: false,
    mitgliedSeit: "2021-09-01",
    email: "simon.keller@example.com",
  },
  {
    mitgliedsnummer: 20,
    vorname: "Tina",
    nachname: "Voigt",
    alter: 29,
    bezahlt: true,
    aktiv: true,
    mitgliedSeit: "2023-11-20",
    email: "tina.voigt@example.com",
  },
];
